spring:
  datasource:
    druid:
      url: "jdbc:mysql://47.120.3.16:3306/beer_sell_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false"
      username: "lwy"
      password: "123"
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
      
swagger:
  enable: true
  base-package: "com.beer.sell.portal.app.controller"
  title: "智慧社区管理员Api文档"
  description: "智慧社区综合平台,包含小区物业,商圈等等"
  version: v1.0.0
  name: "XDD"
  url: "www.xxx.com"
  email: "123456"

